version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
  java:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
